language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VER=3.6
  - os: osx
    language: generic
    env: PYTHON_VER=3.7
  - os: linux
    python: 3.6
  - os: linux
    dist: xenial
    python: 3.7
before_install:
- uname -a
- df -h
- ulimit -a
- source devtools/travis-ci/before_install.sh
- python -V
install:
- pip install -U pytest pytest-cov codecov
- pip install -e .
script:
- pytest -v --cov=forcefield_step forcefield_step/tests/
notifications:
  email: false
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    condition: "$TRAVIS_OS_NAME = osx"
    repo: molssi-seamm/seamm_ff_util
    tags: true
  user: seamm
  password:
  secure: "Pqe6T0TP0q+yYZyviooG95c9cV6AALKt3aguUuSc766MQ1HtEgPUFO+BDXvpUV4w9xMPi3lYbMHduoF/EGRhiyUUNYRc7ad+xFU5Yeg/AZSzm2L3nqU1GX17YAHPZWM1FFB0d4r4uJ9sTFTGMgskqxUQZpOv5X2hckcx4EutkQZiSJsBGLhRxzVO75Cgl5SbBYIsSa31NBEoMxYZTFspK3CDc2zxbDcUpmRNZpVGJRtnv4ieW7/B0xSULWiDWyabo/Lo16TRCxpjBo+VgYpORjzJ98HYXt5UDviPMMR1PB5y3yWj4SIqp22tncAauaFFk/L/uuHWA1qKCutCWvUkqDFjJIJHsfcoKqmf0VqQjnKUvzPJ9rbuZ74lFlGT+XWZrQf9vCzIb99213sRMWvBMwVHODLVhss677Vxmf52y2LfIHXpBDbobYryiSZRP9E8ES8LNdo4p6awC3FqQxfHJt9qMl30+ul6s5bob61lM3jNblvnEgvFlgTyo7N569mK3esLhFt7o4hOYloka+ne7MS85kd61jWfAs0h87MQv6DAaQgxtcNC+qBhH1bEEuriarJdDCJHklkq3k8h4n/PG+cNGoebMH7FZhNyn9Wgp8lxh5jfzJBf0G4OWZg3vlN2ZG5WjBsmq72L1g4rLk6aWQR9Rmokq7DHwNx/r4mqeuw="
